services:
  #######################
  # Databáze
  #######################
  db:
    image: postgres:15
    container_name: my-admin-db-dev
    ports:
      - "5432:5432" # Vystavíme port pro lokální připojení (např. DBeaver)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network

  #######################
  # Backend (Python)
  #######################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-admin-backend-dev
    working_dir: /app
    volumes:
      - ./backend:/app # Mapování lokálního kódu
    command: >
      sh -c "pip install -r requirements.txt &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir src"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TARGET_URL=${TARGET_URL}
    depends_on:
      - db
    networks:
      - app-network

  #######################
  # Frontend (SvelteKit)
  #######################
  frontend:
    image: node:20
    container_name: my-admin-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      # Cache pro node_modules, aby se nestahovaly pokaždé
      - node_modules_cache:/app/node_modules
    command: >
      sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173" # Standardní port pro Vite/SvelteKit dev server
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  node_modules_cache: